version: '3.9'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: book_manager
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  web:
    build: .
    volumes:
      - .:/code
      - ./static:/static
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
